bdr: Don't use hack to avoid copying whole tuples when putting them in slots.
The current hack isn't sufficient, instead more widespread changes to the slot
mechanism are required.

This caused errors like:

	ERROR: could not access status of transaction 4294967295
	DETAIL: Could not open file "pg_clog/0FFF": No such file or directory.

when getting a Datum for a tuple with ExecFetchSlotTupleDatum .

Author: Andres Freund