bdr: Prevent null pointer dereference for blank output plugin params
bdr_output would crash with a segfault due to a null pointer dereference
if a parameter was specified but no corresponding value was supplied, e.g.

pg_recvlogical -P bdr_output -S test -d postgres --create
pg_recvlogical -P bdr_output -S test -d postgres --start -f - -o pg_version

This now fails with an ERROR instead of crashing and forcing postmaster
re-init, e.g.

    ERROR:  uint32 parameter "pg_version" had no value