Apply workers should self-unregister if their bdr.bdr_nodes entry is gone
Per report from Brett Neumeier (@bneumeier), when bdr.remove_bdr_from_local_node
removes the bdr.bdr_nodes entry apply workers may continue to restart then immediately
exit with:

    ERROR: Failed to find expected bdr.connections row ...

until the PostgreSQL instance is restarted.

This happens if the node is parted but doesn't receive its 'k' status, if it's
force-parted, or if bdr.remove_bdr_from_local_node() is run so soon after
parting that the node's apply workers don't have time to notice. In all these
cases the bdr.bdr_nodes row we're checking for 'k' status in vanishes, so we assume
we're good to continue.

Refuse to run and self-unregister if there's no row for our node at all, too.

Fixes #263