Improve error message for natts mismatch
The error

    ERROR: XX000: tuple natts mismatch, 15 vs 16

is less than ideally informative. We'll now emit an error like:

    ERROR: 42P10: remote tuple has different column count to local table
    DETAIL: Table "public"."test" has 15 columns on local node (...) vs 16 on remote node (...)
    HINT: This error arises if the number of columns on two nodes differ. This is most commonly caused by unsafe use of the bdr.skip_ddl_replication and/or bdr.skip_ddl_locking settings.

which should be more helpful.

(Backport of 97d8af5 from REL2_0_STABLE)